<?php
/**
 * Created by PhpStorm.
 * User: ca_php_2s11
 * Date: 2018-06-04
 * Time: 10:33
 */
use PHPUnit\Framework\TestCase;
use Svg\Figure\Circle;

class CircleTest extends TestCase
{
    /**
     * @var Circle
     */
    protected $circle;


    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->circle = new Circle(100, 200, 23, 'red');
    }
    public function test_circle ()
    {

        ob_start();
               $this->circle->draw();
               $content = ob_get_contents();
        ob_end_clean();

        $this->assertEquals('<circle cx ="100" cy="200" r="23" fill= "red"/>', $content);
    }
}